<a href="https://colab.research.google.com/github/PaulinaJohn/Calculations_in_Python/blob/main/calculations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
data = [5, 8, 15, 7, 10, 22, 3, 1, 15]

print(np.mean(data))
print(type(data))

from statistics import mode
print(mode(data))

9.555555555555555
<class 'list'>
15


In [ ]:
np.sort(data)
print(np.median(data))


8.0


In [ ]:
data_2 = [5, 8, 15, 7, 10, 22, 3, 1, 15, 2]
print(np.median(data_2))
print(type(data))


7.5
<class 'list'>


In [ ]:
#Mode
from collections import Counter
data_3 = [1, 1, 2, 2, 3, 3, 4, 4]
print(Counter(data_3).most_common())


[(1, 2), (2, 2), (3, 2), (4, 2)]


In [ ]:
data_4 = [1, 2, 3, 3, 3, 4, 5, 6, 6, 6, 7, 8, 9]
print(Counter(data_4).most_common())


[(3, 3), (6, 3), (1, 1), (2, 1), (4, 1), (5, 1), (7, 1), (8, 1), (9, 1)]


In [ ]:
friends_dogs= [1, 1, 2, 3, 8]
print(np.mean(friends_dogs))
print(np.median(friends_dogs))

from statistics import mode
print(mode(friends_dogs))

import statistics


NameError: ignored

In [ ]:
data_5 = [8, 12, 32, 10, 3, 4, 4, 4, 4, 5, 12, 20]
print(np.mean(data_5))
print(np.median(data_5))
print(mode(data_5))

9.833333333333334
6.5
4


In [ ]:
data_6 = [5, 8, 15, 7, 10, 22, 3, 1, 15, 10]
print(np.mean(data_6))
print(np.median(data_6))
print(Counter(data_6))

9.6
9.0
Counter({15: 2, 10: 2, 5: 1, 8: 1, 7: 1, 22: 1, 3: 1, 1: 1})


In [ ]:
data_7 = [5, 15, 3, 3, 8, 10, 12]
print(np.sum(data_7))

sum(data_7[1:])
print(sum(data_7[2:6])/(7-1))


56
4.0


In [ ]:
import numpy as np
nums = [1, 5, 10, 3, 8, 12, 4, 1, 2, 8]
print(np.sort(nums))
print(np.median(nums))


[ 1  1  2  3  4  5  8  8 10 12]
4.5


In [ ]:
num_s = [5, 10, 3, 8, 12, 4, 1, 2, 8]
print(np.sort(num_s))
print(np.median(num_s))

[ 1  2  3  4  5  8  8 10 12]
5.0


In [ ]:
numz = [1, 5, 10, 3, 8, 12, 4]
print(np.var(numz))
print(np.std(numz))

13.551020408163266
3.6811710647786073


In [ ]:
import numpy as np
inv_returns = [12, -2,	10,	0, 7,	3]
print(np.std(inv_returns))

inv_returns_2 = [5, 5, 5, 5, 5, 5]
print(np.std(inv_returns_2))

5.0990195135927845
0.0


In [ ]:
more_data = [15, 4, 3, 8, 15, 22, 7, 9, 2, 3, 3, 12, 6]
print(np.sort(more_data))
print(np.median(more_data))
print(np.mean(more_data))

from statistics import mode

print(mode(more_data))


[ 2  3  3  3  4  6  7  8  9 12 15 15 22]
7.0
8.384615384615385
3


In [ ]:
more_data2 = [15, 4, 3, 8, 15, 22, 7, 9, 2, 3, 3, 12, 6]
print(np.min(more_data2))
print(np.max(more_data2))
print(np.std(more_data2))
print(np.var(more_data2))

2
22
5.824860005428477
33.92899408284024


In [ ]:
from google.colab import data_table
data_table.enable_dataframe_formatter()
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats
from scipy.stats import kruskal
from scipy.stats import spearmanr
!pip install feature_engine
!pip install scikit_posthocs
import io
import re
from feature_engine.imputation import MeanMedianImputer
from scipy.stats import kruskal
from sklearn.preprocessing import PowerTransformer
from sklearn.preprocessing import MinMaxScaler
from sklearn.pipeline import Pipeline
from scipy.stats import boxcox
from pandas import DataFrame
from numpy import exp
from scipy.stats import chi2
import statsmodels.api as sm
from statsmodels.formula.api import ols
from scipy.stats import chi2_contingency 
from sklearn import preprocessing
from sklearn import decomposition
from sklearn.preprocessing import StandardScaler

     |████████████████████████████████| 205 kB 12.2 MB/s 
     |████████████████████████████████| 9.8 MB 75.9 MB/s 
  Attempting uninstall: statsmodels
    Found existing installation: statsmodels 0.10.2
    Uninstalling statsmodels-0.10.2:
      Successfully uninstalled statsmodels-0.10.2


     |████████████████████████████████| 43 kB 1.0 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
  Created wheel for scikit-posthocs: filename=scikit_posthocs-0.6.7-py3-none-any.whl size=37903 sha256=f2eb08bc6c9ed2a3d0b8f6b9549d17e7316a2a416518de51e478b168068e72cf
  Stored in directory: /root/.cache/pip/wheels/b8/21/e6/f39794d4a6ee3d3cc5146ca80b5cd949452ad4a8fde9f6b9fc
Successfully built scikit-posthocs
