<a href="https://colab.research.google.com/github/PaulinaJohn/Calculations_in_Python/blob/main/notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
data = [5, 8, 15, 7, 20, 22, 3, 1, 15]

print(np.mean(data))
print(type(data))

from statistics import mode
print(mode(data))

10.666666666666666
<class 'list'>
15


In [2]:
np.sort(data)
print(np.median(data))


8.0


In [3]:
data_2 = [5, 8, 15, 7, 10, 22, 3, 1, 15, 2]
print(np.median(data_2))
print(type(data))


7.5
<class 'list'>


In [4]:
#Mode
from collections import Counter
data_3 = [1, 1, 2, 2, 3, 3, 4, 4]
print(Counter(data_3).most_common())


[(1, 2), (2, 2), (3, 2), (4, 2)]


In [5]:
data_4 = [1, 2, 3, 3, 3, 4, 5, 6, 6, 6, 7, 8, 9]
print(Counter(data_4).most_common())


[(3, 3), (6, 3), (1, 1), (2, 1), (4, 1), (5, 1), (7, 1), (8, 1), (9, 1)]


In [16]:
friends_dogs= [1, 1, 2, 3, 8]
print(np.mean(friends_dogs))
print(np.median(friends_dogs))

from statistics import mode
print(mode(friends_dogs))

3.0
2.0
1


In [7]:
data_5 = [8, 12, 32, 10, 3, 4, 4, 4, 4, 5, 12, 20]
print(np.mean(data_5))
print(np.median(data_5))
print(mode(data_5))

9.833333333333334
6.5
4


In [8]:
data_6 = [5, 8, 15, 7, 10, 22, 3, 1, 15, 10]
print(np.mean(data_6))
print(np.median(data_6))
print(Counter(data_6))

9.6
9.0
Counter({15: 2, 10: 2, 5: 1, 8: 1, 7: 1, 22: 1, 3: 1, 1: 1})


In [9]:
data_7 = [5, 15, 3, 3, 8, 10, 12]
print(np.sum(data_7))

sum(data_7[1:])
print(sum(data_7[2:6])/(7-1))


56
4.0


In [10]:
import numpy as np
nums = [1, 5, 10, 3, 8, 12, 4, 1, 2, 8]
print(np.sort(nums))
print(np.median(nums))


[ 1  1  2  3  4  5  8  8 10 12]
4.5


In [11]:
num_s = [5, 10, 3, 8, 12, 4, 1, 2, 8]
print(np.sort(num_s))
print(np.median(num_s))

[ 1  2  3  4  5  8  8 10 12]
5.0


In [12]:
numz = [1, 5, 10, 3, 8, 12, 4]
print(np.var(numz))
print(np.std(numz))

13.551020408163266
3.6811710647786073


In [13]:
import numpy as np
inv_returns = [12, -2,	10,	0, 7,	3]
print(np.std(inv_returns))

inv_returns_2 = [5, 5, 5, 5, 5, 5]
print(np.std(inv_returns_2))

5.0990195135927845
0.0


In [14]:
more_data = [15, 4, 3, 8, 15, 22, 7, 9, 2, 3, 3, 12, 6]
print(np.sort(more_data))
print(np.median(more_data))
print(np.mean(more_data))

from statistics import mode

print(mode(more_data))


[ 2  3  3  3  4  6  7  8  9 12 15 15 22]
7.0
8.384615384615385
3


In [15]:
more_data2 = [15, 4, 3, 8, 15, 22, 7, 9, 2, 3, 3, 12, 6]
print(np.min(more_data2))
print(np.max(more_data2))
print(np.std(more_data2))
print(np.var(more_data2))

2
22
5.824860005428477
33.92899408284024
